[package]
name = "rust-core"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
hmac = "0.12"
sha2 = "0.10"
rand = "0.8"
rand_core = "0.6"
flatbuffers = "0.8"
lz4_flex = "0.11"
zstd = "0.12"
x25519-dalek = "2"
