# KAIRO Rust Core - Unified Cargo.toml

[package]
name = "kairo_rust_core"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers = "25.2.10"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.32", features = ["full"] }
# Add other dependencies as needed
