# KAIRO Rust Core - Unified Cargo.toml

[package]
name = "kairo_rust_core"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers = "25.2.10"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.32", features = ["full"] }
chrono = "0.4"
hmac = "0.12"
rand = "0.8"
rand_core = "0.6"
sha2 = "0.10"
lz4_flex = "0.11"
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
bytes = "1.0"
uuid = { version = "1.0", features = ["v4"] }
warp = "0.3"
thiserror = "1.0"
zstd = "0.12"
kairo_core = { path = "./kairo_core" }
