# rust-core/Cargo.toml
[dependencies]
flatbuffers = "23.5.26"
ed25519-dalek = "1.0.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "benchmark_flatbuffers"
harness = false
<<<<<<< Updated upstream
=======

[dev-dependencies]
criterion = "0.5"
>>>>>>> Stashed changes
