[package]
name = "rust-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_core"
crate-type = ["cdylib"]

[dependencies]
flatbuffers = "25.2.10"
ed25519-dalek = "1.0.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
hmac = "0.12.1"
sha2 = "0.10.8"
chrono = "0.4"
thiserror = "1.0"
warp = "0.3"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
criterion = "0.5"
libloading = "0.7"

[[bench]]
name = "benchmark_flatbuffers"
harness = false
