# rust-core/Cargo.toml

[package]
name = "rust-core"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers = "23.5.26"
ed25519-dalek = "1.0.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
warp = "0.3"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "benchmark_flatbuffers"
harness = false
