[package]
name = "kairobot"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
log = "0.4"
simple_logger = "1.16.0"
tokio = { version = "1", features = ["full"] }



[[bin]]
name = "kairobot"
path = "main.rs"
