[package]
name = "kairof"
version = "0.1.0"
edition = "2021"  # ← 2024 → 2021 にするのが無難

[dependencies]
flatbuffers = "25.2.10"
rand = "0.8"
rand_core = "0.6"
kairo_core = { path = "../kairo_rust_core" }
