role_name: Archivist
description: Safeguards records and knowledge for the mesh.
permissions:
  can_initiate: false
  can_analyze: false
  can_integrate: true
  can_audit: false
system_fingerprint: KairoMesh-Local-v1.5
