[package]
name = "kairo_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "kairo_lib"
path = "lib.rs"

[dependencies]
kairo_core = { path = "../../rust-core" }
serde = { version = "1.0", features = ["derive"] }
