[package]
name = "kairo_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
kairo_core = { path = "../../kairo-core" } # 存在しない場合は削除 or 修正

[lib]
path = "lib.rs"
