name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run Rust tests
        run: cargo test --manifest-path rust-core/Cargo.toml --verbose
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Python deps
        run: pip install pytest
      - name: Run Python tests
        run: pytest -q
      - name: Validate example logs
        run: python scripts/validate_logs.py --check vov/example_log.jsonl

  flatbuffers_check:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Install flatc
        run: sudo snap install flatbuffers
      - name: Generate FlatBuffers
        run: make generate_schema
      - name: Check for uncommitted changes
        run: |
          git status --porcelain
          if [[ $(git status --porcelain) ]]; then
            echo "FlatBuffers generated files are not up-to-date. Please run 'flatc' and commit the changes."
            git diff
            exit 1
          fi
      - name: Run clippy
        run: cargo clippy --package rust-core
